(xbindkey '("XF86AudioRaiseVolume") "amixer set Master 2dB+ unmute")
(xbindkey '("XF86AudioLowerVolume") "amixer set Master 2dB- unmute")
(xbindkey '("XF86AudioMute") "amixer set Master toggle; amixer set Headphone 93% unmute; amixer set Speaker 93% unmute")
(xbindkey '("XF86AudioMicMute") "amixer set Mic toggle")
(xbindkey '("XF86AudioNext") "mocp -f")
(xbindkey '("XF86AudioPrev") "mocp -r")
(xbindkey '("XF86AudioPlay") "mocp -G")
(xbindkey '("XF86MonBrightnessUp") "xbacklight -inc 10")
(xbindkey '("XF86MonBrightnessDown") "xbacklight -dec 10")
